### ISSUE TITLE
"Built path"??

### ISSUE THREAD

**Issue by wwwhtml** [kiwix/kiwix-hotspot#3]
Hello, 

MacOS:  I am trying to build a Kiwix Hotspot on a Micro SD Card, one of the settings is asking for "Build path:", what do you mean with this? Where do we point it to?

Thank you!

**Comment by rgaudin** [comment]
It's the path, on your computer or an external drive where the process will happen (downloading and stuff).
It is important that this location can allow sufficient space that's why you're asked to select it.

**Comment by wwwhtml** [comment]
Thanks!
