### ISSUE TITLE
[URGENT][REGRESSION] Hotspot application 2.0.4 & 2.0.5 does not open on Windows 10

### ISSUE THREAD

**Issue by niuginidatatech** [kiwix/kiwix-hotspot#4]
Hello
I downloaded the Windows version of the Hotspot installer. I started the installer and the initial extraction dialogue appeared but after extraction nothing happened. The hotspot installer did not appear. 

I have Windows 10
Thanks

**Comment by rgaudin** [comment]
Fixed by 2.0.6 release.

**Comment by kelson42** [comment]
@niuginidatatech Please check https://download.kiwix.org/release/kiwix-hotspot/v2.0.6/ and let us know if you still have problems.

**Comment by niuginidatatech** [comment]
@kelson42  thank alot, v2.0.6 works great
