### ISSUE TITLE
Badly named or deprecated images on download.kiwix.org

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#445]
In GitLab by @Kelson42 on Nov 22, 2019, 11:08

These files should be deleted or renamed properly if still needed:
* https://download.kiwix.org/hotspots/est-numerique_20181214.img
* https://download.kiwix.org/hotspots/orange-master2019.img

**Comment by kelson42** [comment]
@rgaudin This is really an easy one et already quite old. Would be great to fix it.

**Comment by kelson42** [comment]
This images have been removed. Problem gone.
