### ISSUE TITLE
Can´t open the Kiwix Hotspot installer on windows 7

### ISSUE THREAD

**Issue by doulos89** [kiwix/kiwix-hotspot#494]
When i try to run the Kiwix Hotspot installer on Windows 7 (64b), it stops and crashes the installer, so i can´t go foward and can´t make the image/iso of the hotspot.

https://imgur.com/a/aKJz8QX
![Diapositiva4](https://user-images.githubusercontent.com/60124109/72774954-d10d5a80-3bc9-11ea-95d1-0b7ffefc8fc0.JPG)
![Diapositiva3](https://user-images.githubusercontent.com/60124109/72774955-d10d5a80-3bc9-11ea-9837-512d9af50ad4.JPG)

**Comment by rgaudin** [comment]
Thanks ; can you please confirm this is with `2.3` version? We found that bug right after the release and shall be fixed today in `2.3.1`.

**Comment by rgaudin** [comment]
Fixed in 2.3.1
