### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#504]
There is a new, slightly remodeled logo for Kiwix 
https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.svg
The app's icon needs to be updated accordingly

**Comment by DhairyaBahl** [comment]
I would like to work on this issue.

**Comment by rgaudin** [comment]
@DhairyaBahl OK. Please consider comments from #530. Ideally, tackle both together.

**Comment by Popolechien** [comment]
Ah, comments in #530 are in French. I'll clarify in English in a minute.

**Comment by DhairyaBahl** [comment]
@Popolechien https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.png this link in the description of the issue is showing error that this page is deleted.

**Comment by Popolechien** [comment]
Ah yes, we posted an SVG instead. Here it is: 
https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.svg

**Comment by DhairyaBahl** [comment]
@Popolechien Okay Got it . Thanks :)

**Comment by DhairyaBahl** [comment]
@Popolechien The new logo in in svg format where as the old logo is in the format of png !! so should I should replace it i guess. There must not be any issue right ?

**Comment by Popolechien** [comment]
@DhairyaBahl svg is simply easier to export into png from Wikimedia Commons (rather than the opposite). I'm not too familiar with what the default format should be in the app itself. If png worked last time let's keep using it :-)

**Comment by DhairyaBahl** [comment]
@Popolechien Okay, thanks a lot for guiding. :)

**Comment by rgaudin** [comment]
Done in #569
