### ISSUE TITLE
Replace "Register/S'enregistrer" with "Confirm/Compris!" on captive portal

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#505]
Register specifically means that some personal data will have to be entered, which is not the case. We mostly want the user to confirm the understood the instructions.

**Comment by rgaudin** [comment]
OK but FYI, register was chosen exactly because we record on the device that the user (mac address, IP address, browser) requested to get in. And we keep that info for a period of time. That's how the captive portal works.

Doesn't need to reflect on UI wording though.

**Comment by kelson42** [comment]
@Popolechien Any new comment?

**Comment by kelson42** [comment]
@rgaudin @kelson42 Please find an agreement so we can close this ticket please.

**Comment by rgaudin** [comment]
Pretty sure it's already "Agree and continue to kiwix.hotspot".
Will check
