### ISSUE TITLE
Remove ZIM and other labels from landing page display

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#507]
On the hotspot's content listing page there is a lable to indicate zim or other types of file; these have no real informational value and are thus a bit confusing. They should / could be removed with no loss nor regret.

![IMG_9290](https://user-images.githubusercontent.com/21675885/80099873-73ddc800-856f-11ea-8bcb-26838569078d.PNG)

**Comment by kelson42** [comment]
@Popolechien We should think to an alternative setup for these card? Would you have a mockup to propose?

**Comment by rgaudin** [comment]
We removed them on the campus because it doesn't have much value. It's something we copied from ideascube but given the number of apps we have and the fact that all ZIMs are categorized the same, it's value is close to zero and raises more questions than it solves.

**Comment by kelson42** [comment]
Ok, we shoukd just do it, trivial.
