### ISSUE TITLE
typo on label in French

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#508]
One more reason to do away with these tags next to the zim title (#507): Appendre -> App**r**endre
![Capture d’écran 2020-05-01 à 09 16 57](https://user-images.githubusercontent.com/21675885/80789577-a64d7d80-8b8c-11ea-84c9-b5545f6d2a59.png)

**Comment by rgaudin** [comment]
@Popolechien we discussed it when you found that bug in Campus. It's been fixed then 05f0c29115cfc5aa8d50619a9f8b7a5abde92c29
