### ISSUE TITLE
The requested URL "/[file]" was not found on this server

### ISSUE THREAD

**Issue by DBemis** [kiwix/kiwix-hotspot#516]
Kiwix Hotspot Installer Version: 2.3.4
![image](https://user-images.githubusercontent.com/2962564/86863696-b35d8000-c099-11ea-9a4c-c30648d4cecb.png)

Config: [New256gbConfig.txt](https://github.com/kiwix/kiwix-hotspot/files/4887826/New256gbConfig.txt)

MicroSD: Samsung Evo Select 256gb
Device: Raspberry Pi Zero W v1.1
Build info: Built with the Hotspot Installer 2.3.4 x64, on Windows 10 1909, writing directly to the SD Card. I've left the settings as default, other than selecting various static content

Issue:
When attempting to go to any of the items on the Pi via the hot spot, I always get the error "Not found - The requested URL "/[filename]" was not found on this server." This was thought to have been fixed with [issue 515](https://github.com/kiwix/kiwix-hotspot/issues/515), but I am getting the error after building a new image
![image](https://user-images.githubusercontent.com/2962564/86861658-945cef00-c095-11ea-8678-9a06a18cffe7.png)
and
![image](https://user-images.githubusercontent.com/2962564/86863547-6a0d3080-c099-11ea-88bc-9f5045c1efbc.png)

Sample of images on SD Card:
![image](https://user-images.githubusercontent.com/2962564/86861864-0e8d7380-c096-11ea-814f-566c52ecbb0e.png)

Desktop app testing from files on SD Card:
Tried to load wikipedia_en_all_maxi.en.zim:
![image](https://user-images.githubusercontent.com/2962564/86861978-4694b680-c096-11ea-8d93-ceb8e8b895ad.png)

Tried to load ted_en_science.en.zim and got the same as above

Successfully loaded crashcourse_en_all.en.zim
![image](https://user-images.githubusercontent.com/2962564/86862212-c4f15880-c096-11ea-8a4a-fe863ab61f5f.png)

Successfully loaded ted_en_global_issues.en.zim
![image](https://user-images.githubusercontent.com/2962564/86862281-e7837180-c096-11ea-8ed2-7dda98b5562f.png)

Let me know if you need additional info
Thank you!

**Comment by rgaudin** [comment]
Ah. my bad, sorry. I know what this is. Will fix

**Comment by kelson42** [comment]
Arghhhh

**Comment by rgaudin** [comment]
Really sorry about that and the time you wasted on this. The fix wasn't incorporated in 2.3.4 and thus it could not have worked.
It now is in [2.3.5](http://download.kiwix.org/release/kiwix-hotspot/) (kiwix-serve is updated at configure stage). Please kindly retry with that new version.
