### ISSUE TITLE
.apk files fail to install

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#521]
Installed both Math Mathews and Nomad on a card ([L277R5F0E](https://cardshop.hotspot.kiwix.org/orders/L277R5F0E)). The install went fine and hotspot behaved as expected, but when I downloaded both apps and tried to open them (Huawei P20 Lite, Android 9), either the Kiwix app tried to open the apk or once I deinstalled the Kiwix app clicking on the apks in my download folder would simply open them as if they were random folders.

![Screenshot_20200717_171454_com huawei hidisk](https://user-images.githubusercontent.com/21675885/87802937-2ad99f00-c852-11ea-8846-c73c1635566f.jpg)

**Comment by rgaudin** [comment]
Looks like newer android purposely refuse to consider it an APK if the Content-Type wasn't `application/vnd.android.package-archive` which is not set on the nginx version we package (`nginx/1.14.2`).

Easy to fix but will require a new master.
