### ISSUE TITLE
Extend session timeout to at least 60 minutes, possibly no timeout

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#523]
The dominant use case at this stage is that users are there for hourly sessions at least (school session), but more broadly that they don't have competing resources and don't need to be disconnected.

**Comment by kelson42** [comment]
What is the problem exactly? After login as admin?

**Comment by Popolechien** [comment]
No as user. Get disconnected after 15', it's tedious.

**Comment by rgaudin** [comment]
Just to be clear:

* When connecting to the hotspot, you first get the captive portal which gives you a link/url to the welcome page and ask you to continue.
* That's where we *register* people (IP).
* After 15m **of inactivity** your registration expires and so you'll be prompted with the captive portal again.

The goal of the captive portal is to inform users where to go to to find content. If you're inactive for 15mn, chances are you won't be able to go back to the right URL. We can surely increase the timeout, keeping its usage in mind.

**Comment by Popolechien** [comment]
Yep that's fine. Time flies.

**Comment by rgaudin** [comment]
So should change it to 60mn?

**Comment by Popolechien** [comment]
Yes please.

**Comment by kelson42** [comment]
@rgaudin Any chance we could fix this one quickly in 2.4?
