### ISSUE TITLE
Nginx fails to start on boot, but 'sudo systemctl restart ngnix-service' gets it going

### ISSUE THREAD

**Issue by jacycatlin** [kiwix/kiwix-hotspot#528]
Using kiwix-hotspot 2.3.6 on Mint 20 to make an image on a 128Gb Sandisk Ultra for a Raspberry Pi Zero W -

As visible in the attached pics, there is an error or two during boot (pic 1)
Once you log in (can't use the username/pwd I put in the GUI, have to use pi default login) you see the details (pic 2)
Simply restarting the service - no other fixes or adjustments - brings it online as you'd normally expect.

![IMG_20200917_204121](https://user-images.githubusercontent.com/38977373/93461846-b2ae5900-f928-11ea-8ac7-bc329aca18db.jpg)
![IMG_20200917_204441](https://user-images.githubusercontent.com/38977373/93461866-ba6dfd80-f928-11ea-9fa3-3d1929e1d03b.jpg)
![IMG_20200917_204516](https://user-images.githubusercontent.com/38977373/93461874-bcd05780-f928-11ea-81e0-4d290ac5f127.jpg)

Apologies for pics instead of text but I'm in a hurry... thanks for the great software though!

**Comment by kelson42** [comment]
@jacycatlin Thank you for your bug report, Please give a us a few days to give you a proper feedback.

**Comment by rgaudin** [comment]
Thank you for your report and sorry for the delay. Please test again with upcoming version 2.4 once it is out (early next week). You'll notice the service has been renamed `kiwix` meanwhile.

![IMG_6060](https://user-images.githubusercontent.com/57929/114876323-bdad6700-9ded-11eb-9542-0f74b942a5d7.jpg)
