### ISSUE TITLE
Update macOS installer logo

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#530]
The Installer is still using the old logo
![Capture d’écran 2020-09-17 à 14 58 09](https://user-images.githubusercontent.com/21675885/93473424-4a468400-f8f6-11ea-8e09-fd7f0f0fefa2.png)
We could / should probably replace it with the logo that was kindly designed a while back by a user:
![logomark-black-01](https://user-images.githubusercontent.com/21675885/93473665-91347980-f8f6-11ea-8382-eb579700e4f4.png)
(this is a .png but I can provide an .svg if need be)

**Comment by rgaudin** [comment]
What is *the old logo*? That's the only one I know.
I guess you're referring to the *Kiwix* logo that serves as a base for this one. Then we could do a new version based on the new kiwix logo.

The contributed logo your attached has been made for the cardshop (and I think it corresponds better).

To answer the question, no, both can be different. Top one is just a branding we set and bottom one is the app logo.

Share a new logo for the app and/or the dmg background if you want it updated.

**Comment by Popolechien** [comment]
Well both (cardshop and installer) do pretty much the same thing, so it does not strike me as irrelevant. I'd be more wary of logo variants going too far off one another, but in the case at hand we had a ready-made solution to use, so why not.
I'll ping @siemsie and see what they can do.

**Comment by siemsie** [comment]
![Logo-kiwix-cardshop-00](https://user-images.githubusercontent.com/61543885/93992012-52d30a80-fd8d-11ea-8d41-5f09658add49.png)
![Logo-kiwix-cardshop-000](https://user-images.githubusercontent.com/61543885/93992021-55356480-fd8d-11ea-996c-5593cb4898e8.png)
![Logo-kiwix-cardshop-01](https://user-images.githubusercontent.com/61543885/93992028-56669180-fd8d-11ea-907a-448dff2480f6.png)
![Logo-kiwix-cardshop-02](https://user-images.githubusercontent.com/61543885/93992030-56ff2800-fd8d-11ea-8283-9618d2308d94.png)
![Logo-kiwix-cardshop-03](https://user-images.githubusercontent.com/61543885/93992031-5797be80-fd8d-11ea-95da-e573a93ca020.png)
![Logo-kiwix-cardshop-04](https://user-images.githubusercontent.com/61543885/93992032-5797be80-fd8d-11ea-8720-b255a38d9e91.png)
![Logo-kiwix-cardshop-05](https://user-images.githubusercontent.com/61543885/93992037-58305500-fd8d-11ea-977f-dd773031193c.png)
Hello tout le monde – voici quelques premières idées. Feedback? Merci :)

**Comment by rgaudin** [comment]
Merci ! Je les trouve tous très bien. Je préfère quand il y a un peu de couleur vs monochrome seul mais c'est tout.

**Comment by Popolechien** [comment]
Alors plutot le numéro 2, et tant qu'à faire créer un logo d'app qui soit identique / similaire / homogène avec celui qu'on a fait pour macOS dans [230](../../apple/issues/230)

**Comment by rgaudin** [comment]
Attention, ce que tu as partagé c'est pour l'appli macOS/iOS et c'est adapté à ces plateformes. Ici tu as ouvert le ticket avec le screenshot macOS mais on utilise la même icone pour les trois plateformes.
Donc faut vérifier si ça vous va aussi pour les autres plateformes, ou faire des adaptations (on est pas obligé d'avoir la même icone).

**Comment by Popolechien** [comment]
@DhairyaBahl please use logo #2 above but check if it fits on all platforms in terms of size.
@siemsie Can you please create a macOS-specific round button like there is for the reader? 

![Capture d’écran 2020-10-05 à 14 50 00](https://user-images.githubusercontent.com/21675885/95081665-279bd400-071a-11eb-950a-dab821e6c282.png)

**Comment by DhairyaBahl** [comment]
@Popolechien Okay I got it. I am working on the issue. Thanks

**Comment by siemsie** [comment]
@Popolechien Can you check if this doc is ok? I based myself on what I handed in last time... 
[Kiwix-icon-MacOS-Installer.zip](https://github.com/kiwix/kiwix-hotspot/files/5342108/Kiwix-icon-MacOS-Installer.zip)

**Comment by Popolechien** [comment]
@siemsie looks good, thanks!

**Comment by DhairyaBahl** [comment]
@Popolechien Okay I got. Working on it. :)

**Comment by rgaudin** [comment]
Done in #569
