### ISSUE TITLE
Enable usage collection

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#541]
Hotspots should be able to collect -and export- a limited amount of usage metrics:
- number of different devices;
- contents (zim files) being accessed, incl. relative "popularity" (ie how many times each content has been accessed);

The resulting data should be stored locally and/or easy to retrieve from the admin console.

**Comment by kelson42** [comment]
Is that ticket not a duplicate of #510?

**Comment by Popolechien** [comment]
Not exactly (was asking specifically about integrating SolarSpell's code as it's already there), but close enough.
