### ISSUE TITLE
Include Afrikatik binaries

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-hotspot#543]

**Comment by kelson42** [comment]
@rgaudin I guess this have been done via #550?

**Comment by Popolechien** [comment]
Binaries have been updated to correct for some certificate issues. https://nextcloud.kanieba.com/index.php/s/tmNAQZoDMEyaRZb

**Comment by kelson42** [comment]
Today I got new binaries per email (nextcloud link).
