### ISSUE TITLE
Short wifi passwords are not properly handled

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#548]
See e.g., job [L361R5FAF](https://cardshop.hotspot.kiwix.org/orders/L361R5FAF): wifi password is set to `edtech ` (without any special character and the installer fails.
Tried the exact same config without password (ie open wifi) and it worked fine.

**Comment by Popolechien** [comment]
Password had six characters (too short).

**Comment by kelson42** [comment]
It should not crash, keeping ticket open.

**Comment by rgaudin** [comment]
duplicate

**Comment by kelson42** [comment]
This should be fixed in cardshop as well (securing password size).

**Comment by rgaudin** [comment]
it doesn't crash

**Comment by kelson42** [comment]
@rgaudin @Popolechien A bit of clarity in your comments would be welcome. I don't understand:
* what is the exact symtom of the problem
* where is the duplicate.

I have found a duplicate at cardshop level https://github.com/kiwix/cardshop/issues/83 but nothing at kiwix-hotspot installer level.

**Comment by rgaudin** [comment]
there is no crash of the hotspot so nothing to fix here.

**Comment by kelson42** [comment]
Ok, lets try to make it clear: what happens exactly when we put a 6 character long password? It seems that the wifi won't be usable, so we should build a security to avoid that.

**Comment by Popolechien** [comment]
I think it loops back to what was said in https://github.com/kiwix/cardshop/issues/210 : we should prevent users from doing things we do not want them to.

To answer your question, if the password is incorrect (too short, or with special characters), the installer (not the hotspot) fails.

**Comment by kelson42** [comment]
Exactly, we should prevent this in Kiwix-hotspot. The other ticket is at the cardshop.
