### ISSUE TITLE
Larger .zim files not searchable

### ISSUE THREAD

**Issue by Bahusson** [kiwix/kiwix-hotspot#552]
On 256GB image. Around 5GB memory left unused.

There is a problem with english Wikipedia search.

Khan appears to work and Polish wiki even gives you suggestions as you search, but once you try to make a direct search in english wiki it throws a timeout and all I can do is restart device. 
I'm still able to search english wiki by clicking on links however, so it's not entirely broken. It's just something with the search.

**Comment by rgaudin** [comment]
Thank you, there no link between this and the free space available on the card.
This issue is a kiwix-serve issue (hosted in kiwix-tools or kiwix-lib repo) and I believe it's a known issue. @kelson42 will move it accordingly

**Comment by kelson42** [comment]
@Bahusson Does the whole suggestion syste fails or only the fulltext search?

**Comment by Bahusson** [comment]
@kelson42 For full english wikipedia .zim the search suggestions do not appear at all regardless of how long I wait for suggestion to appear. In full polish wiki the suggestion appears instantly.

**Comment by kelson42** [comment]
@rgaudin @Popolechien Can one of you test with aPI zero?

**Comment by rgaudin** [comment]
I can't download such large files and I don't have SD card this large neither. Good to know the Pi0 supports those though.

**Comment by Popolechien** [comment]
I've launched a creation, will report back when tested.

**Comment by kelson42** [comment]
@Popolechien Have been able to reproduce the problem?

**Comment by Popolechien** [comment]
Am still waiting for the card to be generated : got notification that it's been uploaded but I suspect it's now waiting for room on the writer or some similar recurring issue.

**Comment by rgaudin** [comment]
Checked and there was an unrelated issue: the worker couldn't resolve `api.cardshop.hotspot.org`… but the host could. Maybe there had been a change at sloppy that was cached somehow. restarted the worker.

**Comment by kelson42** [comment]
@Popolechien news?

**Comment by Popolechien** [comment]
Finally could give it a look, and basically come up with the same issue as described. 
- Generated card including wikipedia_en_all_maxi (latest version, so probably 2020-11 which should have zstd)
- Ran it on Raspberry Pi W
- Searched for a random topic
- Got 504 Gateway timeout after a minute.
- Pi crashes and needs to be restarted.

**Comment by rgaudin** [comment]
Thanks for the report. Should we move that to kiwix-tools/library?
