### ISSUE TITLE
Fails to build with Command returned non-zero exit status 255

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#567]
From https://cardshop.hotspot.kiwix.org/orders/L482R607B
we got the following worker log:
`Command '[PosixPath('/usr/bin/kiwix-hotspot'), 'cache', '--build', PosixPath('/data'), 'reset']' returned non-zero exit status 255`

Possible reason could be the server crash on the side of download.kiwix.org, however the message is a little cryptic to say the least.

**Comment by kelson42** [comment]
@rgaudin Any idea what happens here? We need at least to triage this before the 2.4 release.

**Comment by rgaudin** [comment]
I have not been able to reproduce nor find the root cause. I suppose it could be due to the library off time (as this checks the library on startup). Closing until this surfaces again.
