### ISSUE TITLE
Installer returns invalid argument for 'name'

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#570]
See job [L498R607D]( https://cardshop.hotspot.kiwix.org/orders/L498R607D) : hotspot name is fairly mundane (zombie_pi), yet the installer crashed

**Comment by kelson42** [comment]
@rgaudin IMO to triage/fix in 2.4.

**Comment by rgaudin** [comment]
Allowed characters for name are `a-z`, `A-Z`, `0-9`, `-` and ` `. There's already a cardshop ticket to prevent user from setting non-allowed names,

**Comment by kelson42** [comment]
I guess @rgaudin means https://github.com/kiwix/cardshop/issues/83
