### ISSUE TITLE
Admin mode is not available

### ISSUE THREAD

**Issue by mrcage** [kiwix/kiwix-hotspot#577]
There is no admin mode available on the kiwix hotspot GUI, even when an admin name and password has been set. 

Reproducible both with kiwix hotspot installer and as well with the card shop.

**Comment by mrcage** [comment]
Sorted, I just saw that in the card shop there is the description that the admin mode is for Ideascube, KA-Lite, Aflatoun, EduPi and Wikifundi. I thought I remembered seeing an admin menu button on the home screen, but I might have been wrong...

**Comment by rgaudin** [comment]
There used to be one very long time ago. It's gone though.
