### ISSUE TITLE
Installation failed multiple times

### ISSUE THREAD

**Issue by BenxProductionz** [kiwix/kiwix-hotspot#578]
My Installation failed three times so far, it´s always failing with: 

> Installation failed: ssh command failed with status 2. cmd: sudo sh -c 'cd /var/lib/ansible/local && /usr/local/bin/ansible-playbook -vvv --inventory hosts --tags rename,reconfigure --extra-vars="@/var/lib/ansible/local/extra_vars.json" main.yml'
![fail](https://user-images.githubusercontent.com/47753465/115862890-fde79780-a434-11eb-958f-fd2cef2a92bd.JPG)

**Comment by BenxProductionz** [comment]
Okay, now I tried to use Version 2.4.0 and now it keeps displaying another error: 

> [2:53:33 PM] Installation failed: wait signal timeout: b'login: '

and I also have the entire log for you attached.
[kiwix log.txt](https://github.com/kiwix/kiwix-hotspot/files/6369627/kiwix.log.txt)

**Comment by rgaudin** [comment]
Thank you @BenxProductionz, I've identified the problem. It's a new bug introduced in 2.4.0 by using a more recent version of qemu. We'll have a new release soon.
