### ISSUE TITLE
Possible to modify wifi password ex-post?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#581]
Currently users choose their wifi password (and SSID) during configuration. Is it possible to modify this password (and maybe SSID) from the PI itself (meaning once the image is up and running on it)?

**Comment by rgaudin** [comment]
As you know, everything is set at creation currently, by design. It would be possible to change it afterwards but it's a discussion we want to have when we design 3.0: do we want more flexibility on-the-pi? To what extent?

**Comment by Popolechien** [comment]
> do we want more flexibility on-the-pi? To what extent?

Good question. Let's park this for 3.0 then. Thanks.
