### ISSUE TITLE
256Gb image vastly exceeds 256 Gb

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#586]
Order https://cardshop.hotspot.kiwix.org/all-orders/6089ad8d98c8bf00234ad3be completed and yielded an image that is 268.4GB in the file explorer & shows 274.8GB in the file properties window. It cannot be flashed onto an SD card because too big.

**Comment by Popolechien** [comment]
Order https://cardshop.hotspot.kiwix.org/all-orders/6089ad9c98c8bf00234ad3f2 (128 Gb) yielded image with 137.4GB in file properties & 134.2GB in windows explorer.

**Comment by rgaudin** [comment]
I'm working on the fix. the new QEMU requirement was overlooked and the change required is a bit more complex.
