### ISSUE TITLE
Zimit-generated files cannot be read/accessed on hotspot

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#598]
I generated an image [L548R6094](https://cardshop.hotspot.kiwix.org/orders/L548R6094) containing the zimit-generated GCFglobal zim: the [zim works perfectly on library.kiwix.org](https://library.kiwix.org/edu.gcfglobal.org_en_all_2021-03) but returns 
![Capture d’écran 2021-05-07 à 11 55 30](https://user-images.githubusercontent.com/21675885/117432888-25f1f300-af2b-11eb-8e9e-4afbfa68ad1e.png)

when trying to access from the hotspot

**Comment by rgaudin** [comment]
https://github.com/openzim/warc2zim/issues/24

**Comment by kelson42** [comment]
@rgaudin Yes, but we have no ticket to have HTTPS running on the kiwix-hotspot right?

**Comment by rgaudin** [comment]
Hotspot doesn't support SW zims. @kelson42 should we exclude `_sw:yes` in the Cardshop for now?

**Comment by rgaudin** [comment]
> @rgaudin Yes, but we have no ticket to have HTTPS running on the kiwix-hotspot right?

Couldn't find any, so I'd say no.

**Comment by kelson42** [comment]
We need to listen on https as well witth a self signed cert.

**Comment by rgaudin** [comment]
> We need to listen on https as well witth a self signed cert.

We already have this. We just need to enable SSL for all vhosts

**Comment by rgaudin** [comment]
And maybe add a wildcard to the cert so that there's only the self-CA that triggers an issue
