### ISSUE TITLE
Offline page of Wikipeetia, Wikipedia in Wayuunaiki

### ISSUE THREAD

**Issue by marieleponti** [kiwix/kiwix-hotspot#601]
Request to create an offline page of Wikipeetia, Wikipedia in Wayuunaiki. It's currently in the incubator @ Wikipedia. 
The wiki language code is guc (https://doc.wikimedia.org/mediawiki-core/master/php/MessagesGuc_8php.html#details)

**Comment by rgaudin** [comment]
@kelson42 can you transfer to zim-request?
