### ISSUE TITLE
Can't install Kiwix hotspot on Sd card

### ISSUE THREAD

**Issue by LuX8712** [kiwix/kiwix-hotspot#602]
i have a 16gb sd card, and i want to install around 12 gb of data on it, with around 2.4 left. I try to run the software, but i get this error 

 Invalid SD card size: 14.4 GiB
SD card size has to be a power of 2, e.g. 16 GiB.
You can resize disk images with 'qemu-img resize <imagefile> <new-size>'

please help. idk what to do

**Comment by rgaudin** [comment]
Which version are you using ? It's in the File / about

**Comment by LuX8712** [comment]
I'm using the latest version of the software, 2.0.

**Comment by Popolechien** [comment]
Latest version is 2.4.3 IIRC
https://download.kiwix.org/release/kiwix-hotspot/

**Comment by rgaudin** [comment]
@LuX8712 I suppose you meant `2.4.0`. Please use the 2.4.3+ version which includes a fix for this.

**Comment by LuX8712** [comment]
this did not work.

**Comment by rgaudin** [comment]
Would you mind being a little more verbose? Do you mean you installed version 2.4.3 and got the same error ?
Could you share a screenshot of the About window displaying the version and paste the log here ? There's a button to copy the log to the pasteboard.

Thank you

**Comment by LuX8712** [comment]
Yes, i installed 2.4.3 and the same error occurred. I will  reattempt this to see if i get the error code again, and post it here.

**Comment by LuX8712** [comment]
[LOG.txt](https://github.com/kiwix/kiwix-hotspot/files/6471249/LOG.txt)

That is the log i copied.



![kiwix version](https://user-images.githubusercontent.com/69026824/118099211-f3b91900-b3a2-11eb-9edc-ce79aa297ff7.PNG)

the version

**Comment by rgaudin** [comment]
Thank you ; will come back to you

**Comment by LuX8712** [comment]
thank you

**Comment by kelson42** [comment]
@LuX8712 we believe to understand the problem and therefore confirm there is a bug. Fix to come soon.
