### ISSUE TITLE
Temporarily cap image size at 128Gb

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#609]
In light of [#513](../../libkiwix/issues/513) which seems to be related to the presence of several large zim files on an image leading the RPi to freeze I would recommend we quickly implement a cap at 128Gb for image creation, let we give people half- or barely functional images until a fix is implemented.

**Comment by kelson42** [comment]
@Popolechien Lets wait a few days to see what is the result of the bug analysis. Maybe this is totally unrelated to the size.

**Comment by kelson42** [comment]
This proposal woukd not solve any problem, so I close it.
