### ISSUE TITLE
New upper limit for devices

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#616]
user reported that they could not connect more than eight devices simultaneously on a RPi 3B+. Are we aware of any upgrade that could explain this (and could there be a fix)?

**Comment by rgaudin** [comment]
Linking #544 and https://github.com/iiab/iiab/issues/823

**Comment by rgaudin** [comment]
@Popolechien could you get confirmation that it cannot **connect** the ninth devices to WiFi ? What does the Device says ? Does it refuses the connection ? Is it getting the WiFi connection but no IP, do it stales in connecting, etc.
It's important we know __exactly__ where that limit is.

We know there is the above-mentioned issue that seems to be driver/firmware originated but it can certainly be something else. According to that ticket, the limit should be 10, not 8.

**Comment by Popolechien** [comment]
@rgaudin Tablet does not see the network and does not list it.

**Comment by rgaudin** [comment]
Thanks. Looks like we should try IIAB's fix (reverting to an older firmware)

**Comment by Popolechien** [comment]
tested with an older device as 9th device and it picked up the signal. so yeah, probably an issue with the newer firmware.
